#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Please provide username, AWS Organizaion ID and MFA Token. Example: aws-cli.sh jdoe 738007773326 123456"
    exit 1
fi

USER=$1
TOKEN=$3
ORG_ID=$2

SESSION=$(aws --profile=default sts get-session-token --serial-number arn:aws:iam::$ORG_ID:mfa/$USER --token-code $TOKEN)
if [ $? -ne 0 ]; then
    exit 1
fi
AWS_ACCESS_KEY_ID=$( echo $SESSION | jq .Credentials.AccessKeyId | sed 's/"//g' )
AWS_SECRET_ACCESS_KEY=$( echo $SESSION | jq .Credentials.SecretAccessKey | sed 's/"//g' )
AWS_SESSION_TOKEN=$( echo $SESSION | jq .Credentials.SessionToken | sed 's/"//g' )
EXPIRY=$( echo $SESSION | jq .Credentials.Expiration | sed 's/"//g' )

echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" > ~/.aws/mfa
echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/mfa
echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> ~/.aws/mfa
echo "source ~/.aws/mfa"

echo "Your session will expire on $EXPIRY"
